version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=weathersubs
      - MONGO_PORT=${MONGO_PORT}
    command: mongod --port ${MONGO_PORT}
    restart: unless-stopped

volumes:
  mongo_data:
